# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oIy6mfoM_Gf0Q0fRwDo0coBEK2OB9iZu
"""

import random

number = random.randint(1, 100)

while True:
    guess = int(input("Guess a number (1-100): "))

    if guess < number:
        print("Too low!")
    elif guess > number:
        print("Too high!")
    else:
        print("You got it!")
        break